### ISSUE TITLE
Alteração do layout do painel de votação.

### ISSUE THREAD

**Issue by tiagomcleao** [CMCuritiba/votacao#104]
Visando possibilitar a legibilidade do painel de votação por parte de todos os presentes às reuniões de comissões, sugerimos uma alteração de layout, dividindo a tela em 2 colunas, conforme figura anexada, incluindo:
-padronização de fonte arial, tamanho 18, para os campos: proposição, ementa, iniciativa, conclusão do relator, votos dos vereadores (nomes e teores) e contagem de votos;
-truncagem do conteúdo dos campos "ementa" e "iniciativa" em até 100 caracteres, adicionando reticências caso atinja o limite aqui citado.
![montagem](https://user-images.githubusercontent.com/48928347/55033994-2cdf7500-4ff3-11e9-9aab-12c216e57e49.jpg)

**Comment by edersoncosta** [comment]
@aleodoni Verifica por gentileza o aumento da fonte por momento, as demais alterações, teremos que discutir em conjunto com o DAC/Deprole

**Comment by aleodoni** [comment]
@edersoncosta, na minha opinião, deveríamos discutir essas alterações entes de tomar alguma decisão pois as mesmas impactam diretamente nos padrões de responsividade do framework de apresentação, fazendo que o mesmo perca as suas principais características.

**Comment by diemello** [comment]
Em conversa com o Robson @tiagomcleao e Ederson, chegamos a conclusão de que o aumento de fontes é inviável. Sendo assim estou alterando o nome da issue.

Quanto ao painel de votação, são necessários ajustes finos devido a não exibição de todas as informações quando existem mais de 5 vereadores votando. @aleodoni É possível algo conforme foi solicitado https://user-images.githubusercontent.com/48928347/55033994-2cdf7500-4ff3-11e9-9aab-12c216e57e49.jpg ou sugere outra solução?

**Comment by tiagomcleao** [comment]
Estamos discutindo um layout visualmente mais leve do que a sugestão que passei. Se chegarmos num consenso e a Jussana aprovar, anexo aqui.

**Comment by tiagomcleao** [comment]
Chegamos ao seguinte layout após feedback de que a sugestão anterior estava poluída, em consenso com as divisões, diretoria e o ok da Jussana:

![montagem v2](https://user-images.githubusercontent.com/48928347/56065180-83b2b180-5d4a-11e9-9192-80b89f7590ec.jpg)

Este layout tem as modificações:

-retirada do cabeçalho “Painel de votação”;
-retirada da informação “(Vereador/a)” da tabela de votos;
-abreviação do voto “Favorável com restrições”;
-truncagem dos campos de ementa e iniciativa em até 30 caracteres, acrescentando reticências após isso. O objetivo é que tenham 1 só linha cada;
-fonte arial tamanho 16 para tudo, com exceção do teor dos votos, tamanho 14 – na tabela e na contagem de votos;
-textos em preto nas contagens de voto, na base do painel, com exceção da abstenção, em branco.

Vejam por gentileza se realmente não é possível aumentar o tamanho da fonte.
Além disso, como o Diego comentou, o objetivo da mudança no layout é fazer tudo caber na tela sem rolagem.

Obrigado desde já.

**Comment by tiagomcleao** [comment]
Fiz vários testes hoje de manhã alterando a resolução e a escala da desktop estendida na TV. Em todos eles os caracteres do painel de votação ficaram mais legíveis, mas o layout ficou bagunçado.
O melhor que consegui foi aumentar o número de pixels dos caracteres nas configurações do Firefox. Mesmo assim, a parte inferior do painel não cabe na tela a partir do 5º voto.

**Comment by DePorto** [comment]
Vamos testar modificações na diagramação do conteúdo desta tela:

- Teste de mudanças no leiaute do PAINEL DE VOTAÇÃO.

    Retirar Topo "Painel de Votação";

    Diminuir margens laterais do quadro;

    Leiaute em duas colunas em vez de duas linhas (40% coluna esquerda, 60% coluna direita)

    Indicação de "VOTO CONTRÁRIO c/ associação ao vereador resp. pela manifestação.

Vamos fechar esta issue e criar outras para segmentar a questão. Esta aqui ficará apenas como referência.
