### ISSUE TITLE
Exibição nos tablets do status da votação

### ISSUE THREAD

**Issue by tiagomcleao** [CMCuritiba/votacao#105]
Para que o vereador presidente saiba o status de cada votação eletrônica sem precisar olhar para trás, onde a TV grande fica suspensa, pedimos que cada tablet exiba, após o vereador ter votado, o status geral da votação.
Sugerimos um layout resumido com o número da proposição em questão, o voto de cada vereador e o status da votação, em conjunto com as informações já acertadas como relevantes – informações de login, por exemplo.
![montagem tablet](https://user-images.githubusercontent.com/48928347/55090404-cfe4cd00-508d-11e9-9cb5-d4ce9d8866cf.jpg)

**Comment by tiagomcleao** [comment]
Segue uma montagem com tamanho de fonte que julgamos adequado para o tablet adquirido em 2018 pela CMC:
![simulação tablet](https://user-images.githubusercontent.com/48928347/55169611-dc335d80-5153-11e9-980e-fd64116c51f1.jpg)

**Comment by DePorto** [comment]
Estas questões de leiaute são diagramadas automaticamente pelo sistema, de acordo com o formato da tela em que o conteúdo é visualizado. Se a tela muda de formato, tamanho, etc., o sistema tem a capacidade de adaptar-se, o que é chamado de responsividade. Deste modo, se amarrarmos a diagramação de uma tela para uma determinada realidade, teremos problema de responsividade, em primeiro lugar. Outro ponto negativo é que para tanto, seria preciso modificar a base de desenvolvimento, que é compartilhada, o que geraria inconsistências no futuro, para este mesmo sistema e outros que usam a mesma base de desenvolvimento.

**Comment by DePorto** [comment]
Conforme determinado em reunião do 27/06 com o pessoal do DAC, vamos tentar mudar a cadeira do presidente da reunião de lugar para facilitar a leitura, sem a necessidade de realizar este ajuste.
