### ISSUE TITLE
Sistema de votação e agenda - separação de acesso Staff e Superusuário

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/votacao#106]
## Descrição
O usuário reporta que só é possível acessar o sistema de votação - para gerenciar reuniões - e agenda online - para cadastrar e editar eventos - da CMC se for atribuído acesso de superusuário. Tal situação é indesejada e a solução demanda desenvolvimento, sendo que o @diemello, alegadamente, já está ciente.

### Requisito 1
Solicita-se não seja mais necessário ter acesso de superusuário para gerenciar reuniões de comissões, bastando ter acessos "Ativo" e "Staff". O pedido se estende ao sistema de agenda online, bastando ter acessos "Ativo" e "Membro da equipe" para cadastrar e editar eventos.

### Requisitante
**Solicitante**: @tiagomcleao
**Setor Solicitante**: Seção De Tramitação Processual
**Referencia**: chamado #437

**Comment by DePorto** [comment]
A gestão de acesso ao sistema de votação é feita da seguinte maneira:
- O usuário requerente acessa a URL do sistema pela primeira vez, aí seu usuário e senha são armazenados pela aplicação.
- Atualmente, todos os usuários do sistema tem o perfil de superusuário, o que possibilita a qualquer um que acesse o sistema conceder permissão de acesso a este usuário requerente.

Em conversa com os servidores : Robson, Tiago, Danielli e Cristina determinou-se que haveria uma modificação nos acessos das permissões de 'Staff' e 'Superusuário'. 

O usuário padrão (Staff) passa a poder abrir e fechar sessões, fechar todas as sessões e emitir relatórios. 
Ao 'superusuário' caberia além destas, a possibilidade de conceder permissão de acesso ao sistema de cotação.

A princípio o servidor Robson, por ocupar a Diretoria das Comissões, seria o único a ter permissão de superusuário. A ele caberia conceder essa permissão a mais algum servidor, a seu critério.

Este ajuste ficou definido e será estudado para implementação pelo @aleodoni .

**Comment by DePorto** [comment]
Em reunião do dia 27/06, ficou acertado que a definição acima está ok da parte do pessoal do DAC.
