### ISSUE TITLE
Relatório de votação: padronização do nome de vereadores para exibição

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/votacao#112]
Padronizar os nomes dos vereadores conforme inserção de votos no SPL-II. Ex.: Carlos Mauro Bobato <> Mauro Bobato; Jose Ortiz Lins <> Zezinho Sabará.

**Comment by DePorto** [comment]
Pessoalmente não entendi corretamente a demanda, se é para usar o apelido do vereador, ou o nome real.

**Comment by tiagomcleao** [comment]
Conforme padrão do SPL-II. 

Em 17/06/2019 14:55, De Porto escreveu: 

> Pessoalmente não entendi corretamente a demanda, se é para usar o apelido do vereador, ou o nome real. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

-- 

Atenciosamente, 

Tiago Leão, Técnico Administrativo
 CÂMARA MUNICIPAL DE CURITIBA
 DIRETORIA DE APOIO ÀS COMISSÕES
 (41) 3350-4752 

-- 
Este e-mail e seus anexos podem conter informações confidenciais e/ou
privilegiadas e seu uso e reprodução depende de prévia autorização da
Câmara Municipal de Curitiba. Caso tenha recebido esta mensagem por
engano, por favor, informe o remetente e remova-a. A instituição não se
responsabiliza pelo conteúdo expresso nesta mensagem, sendo esta
responsabilidade exclusiva do seu autor. 
Câmara Municipal de Curitiba 

 

Links:
------
[1]
https://github.com/CMCuritiba/votacao/issues/112?email_source=notifications&amp;email_token=ALVJMW6V3HU75Z2GGDGTGH3P27FZ7A5CNFSM4HYY5CG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX36WSI#issuecomment-502786889
[2]

**Comment by DePorto** [comment]
Acredito @aleodoni , que seja o caso de buscar outro campo com a nomenclatura do vereador, além do nome real, então.
