### ISSUE TITLE
Caractere inválido na exibição de nome em relatório de votação

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/votacao#118]
Na página de relatório de votação o nome do vereador Dalton José Borba aparece com caractere de codificação inválida.

![dalton_erro_nome_votacao](https://user-images.githubusercontent.com/20687716/66429849-4a07ee00-e9ef-11e9-946b-46efb66dade8.png)

**Comment by aleodoni** [comment]
@DePorto já está corrigido. Alguém cadastrou o nome do vereador fora do padrão UTF-8 no LDAP e o erro se replicou até o BD.

**Comment by Jussana** [comment]
Alexandre, boa tarde!! Os Vereadores têm pedido para que no painel de votação os seus nomes sejam exibidos igual ao SPL. Ou seja, os nomes políticos. Por exemplo: Fabiane Rosa (e não Fabiane Delisie Cabral da Rosa), Pier Petruzziello (e não Pierpaolo Petruzziello)... Alguns, como Toninho da Farmácia, já estão com o nome "de guerra" cadastrado. Outros não.
 
Vocês poderiam fazer essa alteração?
 
Obrigada!

**Comment by aleodoni** [comment]
@Jussana @DePorto 
Bom dia Jussana.

Atualmente os nomes dos vereadores exibidos vem do servidor que gerencia as senhas na rede da CMC. Vamos conversar aqui para ver o que podemos fazer a respeito e te respondemos assim que tivermos uma solução para o problema, ok ?
