### ISSUE TITLE
Tela de liberação de projetos para votação

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/votacao#12]
# Descrição
O administrador do sistema, ao acessar esta tela, receberá uma lista das reuniões marcadas para o dia (somente para o dia). Após selecionar a reunião, a pauta da mesma com os projetos em votação serão listados e o projeto escolhido será liberado para votação.
## Requisito 1
O status do projeto pode ter 3 situações : 
(F)echado - Projeto aguardando liberação para votação
(A)berto - Projeto aberto para votação
(V)otado - Projeto votado
## Requisito 2
O status inicial de cada projeto deve ser (F)echado
## Requisito 3
Quando um projeto é aberto para votação, os demais não poderão ser abertos, até que a votação do primeiro seja encerrada.
## Requisito 4
Quando um projeto for selecionado (abrir para votação, encerrar votação), deverão ser gravados os dados : 
* pac_id - código da pauta
* par_id - código do projeto na pauta
* codigo_proposicao - o próprio
* status - status da proposição (ver requisito 1)

**Comment by edersoncosta** [comment]
@aleodoni Pelo que pude observar a tela está perfeita, precisamos assim que possível publicar para avaliação do DAC, mas entendo que não necessitará de mudanças. Pelo menos nada drástico.

**Comment by edersoncosta** [comment]
@diemello Peça acesso ao Alexandre para validar essa tela por gentileza.

**Comment by aleodoni** [comment]
@edersoncosta @diemello @Jussana

Tela de liberação para votação : https://votacao.staging.cmc.pr.gov.br/admin/liberacao/

Deixei fixo para o dia 05/09 apenas para testarmos.

A primeira vez que vcs entrarem no sistema, será pedido login/senha. É o mesmo da rede. Feito isso, libero as permissões para vcs acessarem a tela.

**Comment by aleodoni** [comment]
Pessoal, vou fechar essa issue pois a primeira versão da tela já foi liberada no staging. Em caso de correções, abrimos issues pontuais.
