### ISSUE TITLE
Alterar integração Elotech/LDAP

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/votacao#120]
**O que você gostaria de adicionar:**

Substituir a integração com a Elotech que hoje interliga os campo `pessoa` no **mscmc** e `employeeNumber` no **LDAP** para o campo `cpf` no **mscmc** mantendo o campo `employeeNumber` no **LDAP**.

**Por que isso é necessário?**

Isto é necessário para permitir a correta utilização dos campos no LDAP.

**Sua melhoria está relacionada com algum problema no sistema? Descreva**

N/A

**Contexto Adicional**

Esta alteração deve acontecer de forma síncrona com:

1. Atualização dos valores dos campos no LDAP; e
1. Alteração de configuração no Login Único da Elotech para ler o CPF do campo correto no LDAP.

**Comment by brunosoli** [comment]
Para esclarecer, hoje temos:

- Votação integra login do LDAP com as informações da Elotech através do módulo de autenticação usando o campo employeeNumber/LDAP
- No LDAP o campo employeeNumber que está preenchido com o ID Pessoa do usuário na Elotech
- Segundo regra de negócio do IDaaS da Serpro, para um usuário receber a licença do GSUITE ele precisa ter o CPF informado (ele vai buscar o CPF no campo employeeNumber)

A sugestão é alterar a integração para utilizar o CPF como identificador único do usuário nos 4 serviços: Votação, LDAP, Elotech e Serpro. Isto implica em:

- Substituir no LDAP o valor no campo employeeNumber para o CPF da pessoa
- Alterar o campo de autenticação no Votação e/ou módulo de autenticação
- Alteração de configuração no "Login Único" da Elotech para ler o CPF do campo employeeNumber do LDAP (podemos agendar a qualquer tempo com o Suporte da Elotech)

**Obs**: apesar da issue estar aberta aqui, talvez a alteração seja apenas no código do Votação e/ou do módulo de autenticação do Votação (django-cmcldapauth) e/ou algum outro. Se for o caso, basta migrar/replicar a issue para o repo correto. Talvez seja o caso também de apenas ajustar a configuração dos campos no módulo? Estas questões o @aleodoni vai saber melhor.

**Comment by aleodoni** [comment]
@brunosoli 
Conforme conversamos anteriormente, estas alterações vão impactar nos módulos :
- Votação
- Autenticação (este módulo foi feito em separado pois era usado nos outros sistemas feitos em Django como calendário, chamados)
- CMCLDAPAuth

Eu preciso dar uma olhada no sistema de votação e nos outros 2 módulos para verificar exatamente o que deve ser feito para a alterar esses caras.

Alguns pontos que preciso confirmar:

1. O login será feito através de CPF/senha ?
2. TODOS os usuários contém o campo CPF preenchido no banco de dados? e esses batem com o LDAP?

Acho que esta issue pode ficar aqui mesmo, já que apenas o sistema de votação está ativo; chamados e calendário não estão sendo usados mais, correto ?

**Comment by brunosoli** [comment]
Certo, chamados e calendário estão fora da jogada.

Os pontos:

1. O login continua sendo usuário e senha do LDAP. O que muda é a integração, por baixo dos panos, do LDAP com Elotech;
1. Sim, todos os usuários possuem o CPF cadastrado, mas hoje no campo `employeeType`. Podemos:
   1. Alterar o valor dos campos (atribuir o CPF no campo `employeeNumber`) para alguns usuários (eu, você e o Deini, por exemplo?) para validar a alteração; e
   1. Sincronizar a atualização dos campos no LDAP em lote para todos os usuários (já temos o script de atualização pronto) com a aplicação destas correções.

**Comment by aleodoni** [comment]
Beleza. Vou então dar uma olhada no código pra relembrar as coisas e vou te avisando
