### ISSUE TITLE
Implementação/ Manutenção de estrutura no servidor staging para deploy do votacao.

### ISSUE THREAD

**Issue by fderosso** [CMCuritiba/votacao#121]
É necessário adequar a estrutura do servidor staging para deploy do sistema de votação.
Conversando com o Bruno ele sugeriu um roteiro de como o servidor precisa estar para fazer o deploy.
A partir daí ele faz um playbook simples pra rodar o deploy.

**Comment by aleodoni** [comment]
Será necessário fazer o deploy no staging de 2 projetos:

https://github.com/CMCuritiba/mscmcldap
https://github.com/CMCuritiba/votacao

Ambos possuem o deploy automatizado (staging e prod) utilizando o fabric. 

Verificar também se o BD staging ainda existe. Caso contrário criar um novo.

**Comment by aleodoni** [comment]
Criei uma lista de passos para instalar e configurar a aplicação.
A mesma foi baseada no arquivo de deploy utilizando o Fabric.

https://github.com/CMCuritiba/votacao/wiki/Deploy

**Comment by aleodoni** [comment]
Wikis atualizadas conforme requisitado:

https://github.com/CMCuritiba/votacao/wiki/Deploy---Guia-do-Ameba
https://github.com/CMCuritiba/mscmcldap/wiki/Deploy---Guia-do-Ameba
