### ISSUE TITLE
Mostrar manifestação selecionada pelo vereador no painel de votação

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/votacao#156]
**Funcionamento atual** 
Durante a votação, quando um vereador vota contrário e seleciona uma manifestação disponível, a descrição da mesma não aparece no painel de votação

**Descrição da melhoria**
Mostrar a descrição da manifestação selecionada pelo vereador no painel de votação

**Sugestão de solução**
Verificar a possibilidade de buscar esta informação no BD e disponibilizar no painel de votação

**Comment by edersoncosta** [comment]
@aleodoni Lembrar, por gentileza, de incluir o resultado com a descrição em quem votou também no relatório do sistema.

**Comment by aleodoni** [comment]
@edersoncosta , criei uma issue separada para o relatório.

**Comment by aleodoni** [comment]
@edersoncosta, segue print do painel de votação; veja se é necessário fazer alguma alteração de layout.

![Captura de tela de 2023-09-27 18-06-39](https://github.com/CMCuritiba/votacao/assets/12944198/3c550bd6-d1c8-4c32-8ed6-eb36aacd567d)

**Comment by edersoncosta** [comment]
@aleodoni Estou verificando com minhas chefias imediatas e logo lhe dou retorno.

**Comment by edersoncosta** [comment]
@aleodoni Aprovado, podemos prosseguir.

**Comment by aleodoni** [comment]
@edersoncosta , caso o vereador digite a manifestação :

![Captura de tela de 2023-10-04 11-15-53](https://github.com/CMCuritiba/votacao/assets/12944198/256f2afa-ac5f-4456-b024-d3210eb36fc0)

**Comment by aleodoni** [comment]
@edersoncosta , alterações disponíveis para validação no staging.
Vou encerrar a issue.
