### ISSUE TITLE
Mudança de endereço para administração e vereadores.

### ISSUE THREAD

**Issue by edersoncosta** [CMCuritiba/votacao#159]
Bom dia,

@aleodoni 

Solicito atenção a alteração proposta abaixo:

Substituir:

https://votacao.cmc.pr.gov.br/admin/votacao/
https://votacao.cmc.pr.gov.br/

Respectivamente por:

https://votacao.cmc.pr.gov.br/vereador/
https://votacao.cmc.pr.gov.br/admin/

Essa mudança facilita o entendimento do acesso de cada um e seus papéis.

**Comment by aleodoni** [comment]
@edersoncosta ,

Acredito que era apenas renomear a url referente à votação. Então ficou assim:

Url para os vereadores votarem: 

Atualmente a url é esta: https://votacao.cmc.pr.gov.br/admin/votacao/
Url proposta: https://votacao.cmc.pr.gov.br/vereador/vota

As demais url's se mantém como estão

**Comment by edersoncosta** [comment]
@aleodoni  e qual é a sugestão para a página de ADM? Seguimos como sugeri ou mudará tbm para outra?

**Comment by edersoncosta** [comment]
@aleodoni Em relação a https://votacao.cmc.pr.gov.br/vereador/vota 
Está aprovado.

**Comment by aleodoni** [comment]
@edersoncosta , alterações disponíveis para validação no staging.
Vou encerrar a issue.
