### ISSUE TITLE
PAINEL DE RESULTADO DA VOTAÇÃO

### ISSUE THREAD

**Issue by Jussana** [CMCuritiba/votacao#35]
Criar tela de resultado de cada projeto votado. Formato sugerido em anexo.
[Painel.pdf](https://github.com/CMCuritiba/votacao/files/2390285/Painel.pdf)

**Comment by aleodoni** [comment]
Questões levantadas em conversa com @diemello : 
1. Definição de regra para aprovar, não aprovar, falta de quórum, etc.
2. Quando será disponibilizado o painel ? Apenas na votação que está aberta, selecionando as votações encerradas ou de outra maneira ?
3. Será mostrado na forma de painel ou lista de resultados ?
