### ISSUE TITLE
PRIORIDADE 01 - RELATÓRIO FINAL DE VOTAÇÃO DA REUNIÃO

### ISSUE THREAD

**Issue by Jussana** [CMCuritiba/votacao#36]
Criar relatório final de votação de todos os projetos deliberados em reunião. Formato sugerido em anexo.
[Relatorio Final de Votação.pdf](https://github.com/CMCuritiba/votacao/files/2390300/Relatorio.Final.de.Votacao.pdf)

**Comment by Jussana** [comment]
@aleodoni, conforme conversamos, antes de qualquer outra coisa precisamos que após todos os projetos serem votado, o sistema gere um arquivo para impressão contendo o resultado da votação. Sugiro um modelo ainda mais simplificado, conforme arquivo anexo.
[Relatorio Final de Votação.pdf](https://github.com/CMCuritiba/votacao/files/2406405/Relatorio.Final.de.Votacao.pdf)

**Comment by aleodoni** [comment]
# Levantamento de Requisitos
@diemello, para que possamos discutir e refinar as informações desta issue, vou acrescentar os requisitos  abaixo no formato de dúvida para depois ajustarmos:
## Requisito 1
Método que o usuário seleciona a geração do relatório. Pesquisa as reuniões por data, tipo, etc.
## Requisito 2
Relatório será gerado em PDF? outro formato?
## Requisito 3
Quem terá acesso aos relatórios
## Requisito 4
Ainda não está implementado o processo de voto em separado. Para que o mesmo apareça no relatório, devemos implementar antes do relatório ?

**Comment by Jussana** [comment]
Requisito 1
Método que o usuário seleciona a geração do relatório. Pesquisa as reuniões por data, tipo, etc.
POR REUNIÃO (ex.: 20a. Reunião Ordinária da CCJ)

Requisito 2
Relatório será gerado em PDF? outro formato?
PDF

Requisito 3
Quem terá acesso aos relatórios
ADMINISTRADORES - QUE TODOS OS SEVIDORES DO DAC


Requisito 4
Ainda não está implementado o processo de voto em separado. Para que o mesmo apareça no relatório, devemos implementar antes do relatório ?
NÃO. ENQUANTO O VOTO EM SEPARADO NÃO FOR IMPLEMENTADO NA VOTAÇÃO ELETRÔNICA, PODEMOS FAZER A VOTAÇÃO NO PROJETO FÍSICO SEMPRE QUE HOUVER VOTO EM SEPARADO. MAS, SENDO IMPLENTADO O RELATÓRIO, PODEREMOS UTILIZAR A VOTAÇÃO ELETRÔNICA PARA TODOS AQUELES PROJETOS EM QUE NÃO HAJA VOTO EM SEPARADO.

**Comment by diemello** [comment]
### Requisitos 2,3 e 4 OK
### Requisito 1
@Jussana Precisamos definir melhor este requisito, favor verificar e dar um OK

Sugestão de critérios de pesquisa:
1º por data - exibe abaixo as reuniões dos dias selecionados
2º seleciona a reunião desejada - exibe abaixo as pautas votadas com o botão para imprimir cada uma delas em separado, e abaixo a opção para imprimir todas as votações da reunião selecionada.

**Comment by Jussana** [comment]
@diemello acho que nem precisa ter a opção de imprimir a votação de um projeto isoladamente. Então poderia ficar assim:
1º por data - exibe abaixo as reuniões dos dias selecionados
2º seleciona a reunião desejada - exibe abaixo as pautas votadas com o botão para imprimir todas as votações da reunião selecionada.

**Comment by aleodoni** [comment]
@diemello, @Jussana , por favor, vejam se os requisitos abaixo fecham, ou se precisa adicionar mais alguma coisa.

# Levantamento de Requisitos
## Requisito 1
Filtros para pesquisa/impressão de votações : 
a. Data Início 
b. Data Fim
c. Reuniões (mostrará as reuniões dentro do range das datas de início/fim
Selecionando a reunião, será mostrada lista com as pautas da mesma e botão "Imprimir Resultado" que gerará relatório das pautas votadas.
## Requisito 2
Relatório deverá ser gerado no formado PDF
## Requisito 3
Apenas usuários com perfil admin terão acesso aos relatórios
## Requisito 4
Relatório deverá mostrar as seguintes informações : 
a. Data da reunião
b. Número da reunião
c. Tipo da reunião
d. Comissão
e. Projeto
f. Iniciativa
g. Relator
h. Lista de vereadores e seus respectivos votos
i. Totalizador dos votos

**Comment by Jussana** [comment]
Requisito 1
Filtros para pesquisa/impressão de votações :
a. Data Início
b. Data Fim
c. Reuniões (mostrará as reuniões dentro do range das datas de início/fim
Selecionando a reunião, será mostrada lista com A PAUTA da mesma e botão "Imprimir Resultado" que gerará relatório DOS PROJETOS VOTADOS.

Requisito 2 **OK**
Relatório deverá ser gerado no formado PDF

Requisito 3 **OK** 
Apenas usuários com perfil admin terão acesso aos relatórios

Requisito 4
Relatório deverá mostrar as seguintes informações :
a. Data da reunião
b. Número da reunião
c. Tipo da reunião
d. Comissão
e. **Todos os** Projetos Votados
f. **Respectivas** Iniciativas
g. **Respectivos** Relatores
h. **Conclusão do respectivo Relator**
h. Lista de vereadores e seus respectivos votos **em cada projeto**
i. Totalizador dos votos **de cada projeto**

**Comment by aleodoni** [comment]
@Jussana @diemello @edersoncosta Tela inicial do relatório está disponível em https://votacao-staging.cmc.pr.gov.br/admin/relatorio/votacao/
Ainda estou implementando o relatório em si, mas já disponibilizei a tela para vcs comentarem.

**Comment by Jussana** [comment]
@aleodoni tá ficando ótimo!!! Muito obrigada!

**Comment by aleodoni** [comment]
@Jussana, primeira versão do relatório finalizado. Não consegui colocar hoje no staging pois o mesmo estava gora do ar. De qqr maneira, segue em anexo um pdf gerado pelo sistema. Dê uma olhada para depois conversarmos sobre ajustes/mudanças.
[download (1).pdf](https://github.com/CMCuritiba/votacao/files/2439800/download.1.pdf)
Vou fechar essa issue. Se precisar criamos outra(s) para os ajustes.

**Comment by aleodoni** [comment]
Staging atualizado. Link para acessar relatório : https://votacao-staging.cmc.pr.gov.br/admin/
