### ISSUE TITLE
ORDENAÇÃO DOS PROJETOS NA TELA DE INCLUSÃO PARA VOTAÇÃO

### ISSUE THREAD

**Issue by Jussana** [CMCuritiba/votacao#37]
Incluir na lista dos projetos pautados a coluna "RELATOR", possibilitando ainda que os projetos sejam ordenados com base nessa coluna.

**Comment by aleodoni** [comment]
@Jussana @diemello @edersoncosta 
A ordem das colunas ficaria assim ?
```
Projeto
Iniciativa
Relator
```

**Comment by Jussana** [comment]
Pode ser essa ordem sim, @aleodoni
