### ISSUE TITLE
Voto Contrário

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/votacao#41]
## Descrição
Botão do voto contrário deverá trazer uma lista com os votos em separado

### Requisito 1
Deverá exibir todos os votos em separado cadastrados no SPL

### Requisito 2
Caso seja incluído um voto em separado durante a votação aberta, este deverá ser incluído na lista

### Requisito 3
Caso exista mais de uma manifestação cadastrada no SPL para o vereador, considerar a mais recente.

### Requisito 4
A lista deverá exibir o nome do vereador e a conclusão proposta.

**Comment by aleodoni** [comment]
Query utilizada é a spl.texto_conclusao_autor

**Comment by aleodoni** [comment]
@diemello, preciso que me dê permissão para acessar a tabela ```texto_conclusao_autor```. Estou recebendo a seguinte mensagem quando tento criar o dblink : 
```ERRO:  permissão negada para relação texto_conclusao_autor```
