### ISSUE TITLE
Tela de votação

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/votacao#6]
![20180904_174543](https://user-images.githubusercontent.com/12944198/45057197-62c70700-b06b-11e8-928e-b3abb8dc9e51.jpg)

**Comment by aleodoni** [comment]
@edersoncosta @diemello
Segue em anexo prévia da tela de votação. Por favor contribuam.
![screenshot at 2018-09-11 16 22 13](https://user-images.githubusercontent.com/12944198/45382679-5b5dab80-b5df-11e8-9e1b-26008c23a9d4.png)

**Comment by Jussana** [comment]
@aleodoni acho que só falta incluir o tipo de conclusão da manifestação: Trâmite, Conhecimento, Arquivamento...

**Comment by aleodoni** [comment]
@diemello @Jussana, tenho 2 campos de retorno de conclusão : a do relator e a da comissão. Acredito que seja o do relator, confirma ?

**Comment by edersoncosta** [comment]
@aleodoni :  Acredito que podemos colocar a Iniciativa junto com o número da proposição ganhando espaço para descrição do projeto, o que acha @Jussana?

**Comment by Jussana** [comment]
@aleodoni é o campo de conclusão do relator mesmo.

**Comment by aleodoni** [comment]
@Jussana @edersoncosta @diemello Ok.

**Comment by aleodoni** [comment]
@edersoncosta @diemello @Jussana

Tela de  votação : https://votacao.staging.cmc.pr.gov.br/admin/votacao/

Deixei fixo para o dia 05/09 apenas para testarmos.

A primeira vez que vcs entrarem no sistema, será pedido login/senha. É o mesmo da rede. Feito isso, libero as permissões para vcs acessarem a tela.

**Comment by aleodoni** [comment]
Pessoal, vou fechar essa issue pois a primeira versão da tela de votação já foi disponibilizada. Para ajustes, correções, etc, abrimos issues pontuais.
