### ISSUE TITLE
Fechamento automático de reuniões

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/votacao#65]
**Descrição**
Fechar automaticamente reunião que tenha ficado aberta de até 7 dias anteriores

**Comment by aleodoni** [comment]
@diemello, conforme conversamos, acredito que a melhor opção é a verificação diária do sistema (madrugada) e fechar as votações que ficaram abertas. Assim, no dia seguinte, o sistema está OK.

**Comment by aleodoni** [comment]
## Requisito 1
Toda votação que não foi fechada durante o dia, deverá ser fechada automaticamente pelo sistema.
## Requisito 2
Essa verificação será feita de madrugada, para garantir que nenhum usuário esteja utilizando o sistema e que a votação que esteja aberta tenha essa condição por motivo de esquecimento.

**Comment by aleodoni** [comment]
Implementado e reforçado na issue #69
