### ISSUE TITLE
ajuste no layout da tela de votação

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/votacao#66]
Verificar a necessidade de colocar o brasão da CMC na tela de votação dos vereadores

**Comment by diemello** [comment]
@jussana, favor colocar os requisitos para exibição do cabeçalho conforme nossa conversa em _06/11 17:30_(Ex: adicionar nome ou login utilizado para acesso, criar botão de SAIR para "deslogar" do sistema) 
necessário o brasão da CMC? nome do sistema?

**Comment by Jussana** [comment]
Boa tarde! @aleodoni @diemello 
Concordo com a inclusão do brasão da Câmara. Além disso, precisamos que na tela de votação esteja identificado o Vereador logado no sistema, bem como a opção de "sair" (logout).
De resto, podemos manter como está.

**Comment by aleodoni** [comment]
Pessoal, por favor validem o layout. Acabei de atualizar o staging. Vou fechar essa issue e se precisar abrimos outra para ajustes.
