### ISSUE TITLE
Voto em Separado em Reunião

### ISSUE THREAD

**Issue by Jussana** [CMCuritiba/votacao#81]
Criar mais um botão na tela de votação para inserção de voto em separado no momento da reunião. Clicando nesse botão, abre uma lista com todas as opções de conclusão. O vereador seleciona das opções e confirma. Após confirmar, esse tipo de conclusão escolhida passará a constar, juntamente com o nome desse Vereador, na lista que do botão "Voto Contrário".

**Comment by DePorto** [comment]
Quais são as opções a selecionar?

**Comment by tiagomcleao** [comment]
Basicamente são as conclusões elencadas no SPL-II, que têm atendido ao processo legislativo, com exceção de "não votado/concluído" e "votado sem maioria", que atendem ao regimento interno mas não são opções de voto:

Contrário
Pela anexação
Pela derrubada do veto
Pela devolução ao autor
Pela elaboração do projeto
Pela manutenção do veto
Pela reanálise por comissão específica
Pela tramitação
Pelo arquivamento
Pelo encerramento
Por mais informações

Fico à disposição.

**Comment by DePorto** [comment]
Voto em separado. Sobre este item será necessário uma conversa mais específica, para avaliar o tratamento dos manifestações, e do tipo de voto

  - Manifestação do relator e Manifestação em separado
  
  - Tipo das manifestações: 'Favorável', 'Favorável com Restrições' e 'Contrário'

Da análise desta issue, saiu a necessidade de criar uma interface no SPL para cadastrar manifestações em separado durante o período de reunião/votação, de modo que não haja necessidade de criar um trâmite de 'pedido de vistas' que fica abaixo do prazo regimental (que é de 4 dias). Feita essa manifestação durante a reunião, o sistema de votação puxaria automaticamente este item junto à manifestação do relator e demais previamente cadastradas para que estas apareçam na janela de escolha pelos vereadores na hora da votação.
