### ISSUE TITLE
Melhorias no Layout do Relatório de Votação

### ISSUE THREAD

**Issue by Jussana** [CMCuritiba/votacao#83]
1 - Aumentar o tamanho da fonte

2 - Negritar e sublinhar o Título "Como votaram os vereadores"

3 - Ordenar os nomes dos vereadores em ordem alfabética ou conforme SPL-II

4 - Aumentar a margem esquerda do relatório, pois quando o mesmo é anexado ao projeto, parte dos nomes dos vereadores fica oculta

5 - Padronizar os nomes dos vereadores conforme inserção de votos no SPL-II. Ex.: Carlos Mauro Bobato <> Mauro Bobato; Jose Ortiz Lins <> Zezinho Sabará

6 - Inserir quebra de página após cada projeto votado, de forma que cada resultado de votação apareça em uma folha separada

**Comment by edersoncosta** [comment]
@aleodoni  Sobre o item 6 - Inserir quebra de página após cada projeto votado, de forma que cada resultado de votação apareça em uma folha separada.

Como podemos dar prioridade para o mesmo? Por gentileza, peço que o faça.

**Comment by aleodoni** [comment]
@edersoncosta, você decide a prioridade ;-)

**Comment by edersoncosta** [comment]
@aleodoni A prioridade foi dada pela @Jussana , então podemos seguir com isso.

**Comment by aleodoni** [comment]
@edersoncosta, @Jussana , @diemello 
Alteração feita e será disponibilizada no staging até final do dia 16/04/2019.
Para testar a alteração, pode ser escolhido relatório do dia 30/10/2018, 25a Comissão de Constituição e Justiça.

**Comment by aleodoni** [comment]
@edersoncosta , @Jussana , @diemello 
https://votacao-staging.cmc.pr.gov.br/admin/relatorio/votacao/
Staging já atualizado para validação do item 6 desta issue

**Comment by DePorto** [comment]
Essa issue será fechada os itens de 1 a 6 serão quebrados em issues separadas para melhor gerenciamento.
