### ISSUE TITLE
Ajustes no Layout da Tela de Votação

### ISSUE THREAD

**Issue by Jussana** [CMCuritiba/votacao#88]
@aleodoni se for possível diminuir o espaçamento existente entre os campos "iniciativa", "ementa" e "conclusão", e também diminuir aquela linha azul onde consta o número do projeto, agradeço! Pois dessa forma acredito que a tela de votação aparecerá inteira, sem que seja preciso rolar a página para que os Vereadores consigam votar.

Obrigada!

**Comment by aleodoni** [comment]
@Jussana, fiz as alterações com algumas ressalvas: 
Em relação ao espaçamento entre "iniciativa", "ementa" e "conclusão", não há a possibilidade de alterar o mesmo, pois é padrão do framework; de qualquer maneira, diminuí o tamanho da fonte para que a tela ficasse sem rolagem.
As alterações serão carregadas no staging para que vocês possam validar as mesmas.
Vou fechar essa issue e caso necessário podemos reabri-la.
