### ISSUE TITLE
Definição Tipos de Votação

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/votacao#9]
# Descrição
Issue para definirmos os tipos de votação e os requisitos/funcionamento das mesmas.

## FAVORÁVEL
Grava no voto tipo de votação 'F'

## FAVORÁVEL COM RESTRIÇÕES
Grava no voto tipo de votação 'R' e abre espaço para digitar texto.

## CONTRÁRIO
Grava no voto tipo de votação 'C'

## ABSTENÇÃO
Grava no voto tipo de votação 'A'

## VISTA
Grava no voto tipo de votação 'V'

**Comment by Jussana** [comment]
@aleodoni FAVORÁVEL COM RESTRIÇÕES

Podemos incluir campo de inserção de texto contendo as restrições ao voto favorável.

**Comment by aleodoni** [comment]
Pessoal, vou fechar essa issue e criar uma específica para tratar o voto FAVORÁVEL COM RESTRIÇÕES
